[package]
name = "zs_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
zs_core = { path = "../core" }

[lib]
proc_macro = true